In [26]:
l=[1,2,3,4,5]
type(l)

list

In [35]:
l.append(11)

In [28]:
print(l)

[1, 2, 3, 4, 5]


In [22]:
l.clear()

In [36]:
l.count(11)

3

In [37]:
import numpy as np

In [38]:
import pandas as pd

In [39]:
help(l)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [42]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
my_list1=[1,2,3,4,5]

In [44]:
my_array=np.array(my_list1) # This way we can create a array from the list
my_array

array([1, 2, 3, 4, 5])

In [46]:
mylist2=[11,22,33,44,55]
my_array2=np.array(mylist2)
my_array2

array([11, 22, 33, 44, 55])

In [51]:
my_lists=[my_list1 + mylist2]
my_lists

[[1, 2, 3, 4, 5, 11, 22, 33, 44, 55]]

In [52]:
my_lists=[my_list1, mylist2]
my_lists

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [54]:
my_array=np.array(my_lists)
my_array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [59]:
my_array.dtype

dtype('int64')

In [63]:
my_array.shape# gives the no.of columns and the rows count of the array

(2, 5)

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [2]:
import numpy as np
np.empty(3)

array([3., 2., 1.])

In [71]:
data_type=np.empty(3)

In [72]:
data_type.dtype

dtype('float64')

In [75]:
np.ones([5,5]) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.ones(2)

array([1., 1.])

In [77]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
np.eye(5) # Createting Identity of Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.arange(4,10) #start at 4 end at 10

array([4, 5, 6, 7, 8, 9])

In [88]:
np.arange(1,10,2) #start at 1 end at 10 interval is 2

array([1, 3, 5, 7, 9])

In [1]:
import numpy as np

In [7]:
list = [1,2,3,4,5]
list2 = [11,22,33,44,55]
my_lists=[list, list2]
my_array=np.array(my_lists)
my_array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [9]:
list.clear()

In [8]:
list

[1, 2, 3, 4, 5]

In [10]:
my_array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [19]:
5/3

1.6666666666666667

In [25]:
my_array=np.array([[1,2,3,4,5], [11,22,33,44,55]])

In [26]:
my_array

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [27]:
my_array * my_array

array([[   1,    4,    9,   16,   25],
       [ 121,  484, 1089, 1936, 3025]])

In [28]:
1 / my_array

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.09090909, 0.04545455, 0.03030303, 0.02272727, 0.01818182]])

In [31]:
my_array ** 3

array([[     1,      8,     27,     64,    125],
       [  1331,  10648,  35937,  85184, 166375]])

In [33]:
my_array=np.array([[1,2,3,4,5],[12,13,14]])

/var/folders/t7/zv08vvlj7zn5b8yc7ywj4tl80000gn/T/ipykernel_1014/511243254.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  my_array=np.array([[1,2,3,4,5],[12,13,14]])


In [34]:
my_array

array([list([1, 2, 3, 4, 5]), list([12, 13, 14])], dtype=object)

In [51]:
arr=np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr= arr[0:5]

In [54]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [55]:
arr[0:4] = 100

In [56]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [59]:
for i in arr:
    if arr[0:4] == 100:
        arr = np.arange(0,4)
        

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[:] = 99

In [62]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [63]:
 arr_copy = arr.copy()

In [64]:
arr.copy

<function ndarray.copy>

In [126]:
arr_2d = ([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [132]:
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [134]:
arr_2d[]

[[7, 8, 9]]

In [79]:
arr_2d[0][2] = 0

In [88]:
arr_2d

[[1, 2, 0], [4, 5, 6], [7, 8, 9]]

In [136]:
arr_2d =np.zeros((10,10))

In [117]:
arr_2d =np.ones((10,10))

In [137]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [140]:
for i in arr_2d:
    arr_2d[i] = 1

IndexError: arrays used as indices must be of integer (or boolean) type

In [147]:
"he is a \"guy\" good"

'he is a "guy" good'

In [158]:
x = int(input("Enter the input "))
print ("\n", x)

Enter the input 23

 23


In [1]:
list = [5,6,7,9,8]

In [2]:
list

[5, 6, 7, 9, 8]

In [161]:
list[0]

5

In [3]:
max(list)

9

In [7]:
for i in list:
    if list == max(list):
        print (max(list))
        

In [8]:
i

8

In [14]:

marks = int(input("Please enter the marks for grade"))
if marks >= 90:
    print("Passed in distinction")
elif marks >= 70:
    print("Passed in first class")
elif marks >= 50:
    print ("Passed in second class")
elif marks >= 30:
    print("Passed in third class")
else :
    print("Failed")
 

Please enter the marks for grade49
Passed in third class


In [17]:
list = [1,2,3,4]
list[0]

1

In [30]:
list1 = ["Omkar", "Roja"]

In [37]:
lists = [list+ list1]

In [52]:
list * 3

[1, 100, 3, 4, 1, 100, 3, 4, 1, 100, 3, 4]

In [3]:
x = input("enter the fruit name: ")
fruits = ["Roja", "apple", "Mango", "Supporta", "Dragon", "Kiwi"]
for i in fruits :
    print ("Fruit name is : " + x)
else :
    print("No Fruit specified in the list")

enter the fruit name: apple
Fruit name is : apple
Fruit name is : apple
Fruit name is : apple
Fruit name is : apple
Fruit name is : apple
Fruit name is : apple
No Fruit specified in the list


In [ ]:
print("apple" in fruits)

In [1]:
fruits=["🍎", "🍊 ", "🥭", "🍇 "]

In [2]:
fruits

['🍎', '🍊 ', '🥭', '🍇 ']

In [4]:
fruits1=["Apple", "Orange", "Mango"]
fruits1

['Apple', 'Orange', 'Mango']

In [5]:
fruits1.index("Mango")

2

In [12]:
fruits1.insert(1,"Dragon")

In [13]:
fruits1

['Apple', 'Dragon', 'Banana', 'Orange', 'Mango']

In [15]:
fruits1.index("Orange")

3

In [28]:
import numpy as np

In [27]:
x=np.arange(0,10)

NameError: name 'np' is not defined

In [30]:
pip3 install numpy

SyntaxError: invalid syntax (3889239008.py, line 1)

In [33]:
x=list(range(1,20,2))

In [34]:
x

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
def function():
    marks = int(input("Please enter the marks for grade"))
    if marks >= 90:
        print("Passed in distinction")
    elif marks >= 70:
        print("Passed in first class")
    elif marks >= 50:
        print ("Passed in second class")
    elif marks >= 30:
        print("Passed in third class")
    else :
        print("Failed")
 

In [40]:
function()

Please enter the marks for grade23
Failed


In [10]:

def even(x):
    #for x in range(-5,21):
     #   print(x)
        if (x%2 == 0):
            print("Even number")
        elif (x%2 != 0):
            print("Odd number")
        else:
            print("negetive number passed" + x)


In [13]:
even(-4)

Even number


In [94]:
def bank_login(userID, Pass):
    username = input("Enter userId  ")
    Password = input("Enter Password consisting of 8 to 16 characters including special cases  ")
    if userID == username and Pass == Password:
        print("Login successful")
    else :
        print("Login Failed")

In [97]:
bank_login("omkar", "Re1992")

Enter userId  Omkar
Enter Password consisting of 8 to 16 characters including special cases  Re1992!@#
Login Failed


In [99]:
bank_login("roja","omkar")

Enter userId  Roja
Enter Password consisting of 8 to 16 characters including special cases  omkar
Login Failed


In [101]:
counter=0
while(counter<=10):
    print(counter)
    counter += 1

0
1
2
3
4
5
6
7
8
9
10


In [106]:
def number_while() :
    counter=0
    while (counter<=10):
        print(counter)
        counter+=1

In [108]:
number_while()

0
1
2
3
4
5
6
7
8
9
10


In [14]:
def compute(a, b):
    print("Summation of a and b is : " + str(a+b))
    print("Subtraction of the a and b is : " + str(a-b))
    print("Multiplication of a and b is " + str(a*b))
    

In [15]:
compute(1,2)
compute(100,200)

Summation of a and b is : 3
Subtraction of the a and b is : -1
Multiplication of a and b is 2
Summation of a and b is : 300
Subtraction of the a and b is : -100
Multiplication of a and b is 20000


In [7]:
def add(a,b):
    c = a+b
    return c

In [11]:
result= add(1,2)
print(result)
result= add(100,200)
print(result)

3
300


## Passing one function as an argument to another function

In [17]:
def add(a,b):
    return a+b # we are avoiding adding one more varibale c to store the values of a&b. Optimization of code
def square(c):
    return c*c

In [18]:
square(add(10,20))

900

In [44]:

def random_count():
    import random
    for i in range(6):
        return random.randint(1,6)

In [45]:
result=random_count()
print(result)

2


In [41]:
for i in result:
    print(i.count)

TypeError: 'int' object is not iterable

In [92]:
find_count()

3
6
3
1
6
6
[None]


In [47]:
fruits = ['apple', 'banana', 'orange', 'apple', 'kiwi', 'apple']
count_apple = fruits.count('apple')
print(count_apple)

3


In [48]:
def wethit(weight, height):
    bmi = (weight / height)^2
    return bmi
    

In [49]:
wethit(80,45)

TypeError: unsupported operand type(s) for ^: 'float' and 'int'

In [63]:
import random
from collections import Counter

# Generate a list of random integers
random_integers = [random.randint(0, 10) for _ in range(20)]

# Count the occurrences of each integer using Counter
counts = Counter(random_integers)

# Print the counts
for integer, count in counts.items():
    print(f"{integer}: {count}")


0: 2
4: 5
7: 5
5: 1
8: 1
2: 2
9: 2
10: 1
6: 1


In [9]:
def bmi():
    weight = float(input("Enter the weight in Kg : "))
    height = float(input("Enter the height in meters : "))
    bmi = (weight )/ pow(height,2)
    print(bmi)

In [10]:
bmi()

Enter the weight in Kg : 76.6
Enter the height in meters : 1.75
25.01224489795918


In [13]:
def calculate_bmi(weight, height):
    bmi = weight/pow(height, 2)
    return bmi
wt = float(input("Enter the weight in kg : "))
ht = float(input("Enter the height in meters : "))
bmi = calculate_bmi(wt, ht)
print(bmi)

Enter the weight in kg : 75
Enter the height in meters : 1.75
24.489795918367346


In [16]:
try:
    a=20
    b=0
    print(a/b)
except ZeroDivisionError:
    print("You will encounter the ZeroDivisionError")

You will encounter the ZeroDivisionError


In [17]:
try:
    a=20
    b=0
    print(a/b)
except ZeroDivisionError:
    print("You will encounter the ZeroDivisionError")
finally:
    print(" No matter what code in the finally block will be executed even if the exception handled or not handeled")

You will encounter the ZeroDivisionError
 No matter what code in the finally block will be executed even if the exception handled or not handeled


In [18]:
try:
    a=20
    b=10
    print(a/b)
except ZeroDivisionError:
    print("You will encounter the ZeroDivisionError")
finally:
    print(" No matter what code in the finally block will be executed even if the exception handled or not handeled")

2.0
 No matter what code in the finally block will be executed even if the exception handled or not handeled


In [1]:
pwd

'/Users/omkar/Desktop/Coding/Udemy/Udemy_python_codenotes'

In [2]:
ls


Course FAQ.ipynb
Data Project - Election Analysis.ipynb
Data Project - Stock Market Analysis.ipynb
Intro to Data Project Section.ipynb
Intro to Data Projects - Titanic.ipynb
Lec 10 - Array Transposition.ipynb
Lec 11 - Universal Array Function.ipynb
Lec 12 - Array Processing.ipynb
Lec 13 - Array Input and Output.ipynb
Lec 14 - Series.ipynb
Lec 15 - DataFrames.ipynb
Lec 16 - Index Objects.ipynb
Lec 17 -Reindexing.ipynb
Lec 18 -Drop Entry.ipynb
Lec 19 - Selecting Entries.ipynb
Lec 20 - Data Alignment.ipynb
Lec 21 - Rank and Sort.ipynb
Lec 22 - Summary Statistics.ipynb
Lec 23 - Missing Data.ipynb
Lec 24 - Index Hierarchy.ipynb
Lec 25 - Reading and Writing Text Files.ipynb
Lec 26 - JSON with Python.ipynb
Lec 27 - HTML with Python.ipynb
Lec 28 - Excel with Python.ipynb
Lec 29 - Merge.ipynb
Lec 30 -Merge on Index.ipynb
Lec 31 - Concatenate.ipynb
Lec 32 - Combining DataFrames.ipynb
Lec 33 - Reshaping.ipynb
Lec 34 - Pivoting.ipynb
Lec 35 - Duplicates in DataFrames.ipynb
Lec 36 - Mapping.ipynb
L

In [60]:
file = open("lec25.txt", 'w')
#Do something with the file
file.write("Do something with the file")
file.close()


In [61]:
cat lec25.txt

Do something with the file

In [64]:
with open("lec25.txt", "a") as file : # ais append to the text file "w" is overwritten the file content be careful
    file.write("\n This is an another and best way for file handling")
    file.close()

In [65]:
cat lec25.txt

Do something with the fileThis is an another and best way for file handling
 This is an another and best way for file handling

In [70]:
with open("lec25.txt", "r") as file:
    x=file.read()
    print(x)
with open("lec25.txt", "a") as file:
    file.write("\n Best way of reading and writing the file")
    file.close()

Do something with the fileThis is an another and best way for file handling
 This is an another and best way for file handling
 Reading and writing the file
 Reading and writing the file


In [71]:
cat lec25.txt

Do something with the fileThis is an another and best way for file handling
 This is an another and best way for file handling
 Reading and writing the file
 Reading and writing the file
 Best way of reading and writing the file

In [78]:
def divide_function(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        print("This is divided by zero error")
        return 0
x = int(input("Enter the value of A: "))
y = int(input("Enter the value of B: "))
divide_function(x,y)

Enter the value of A: 💯 


ValueError: invalid literal for int() with base 10: '💯 '

In [86]:
def file_handling():
    with open("lec25.txt", "w") as file:
        z = file.write("This is the New Data opened the file and written the data")
        return z
        file.close()

In [88]:
file_handling()

57

In [85]:
cat lec25.txt

This is the New Data opened the file and written the data

In [91]:
def reading():
    with open("lec25.txt", "r") as file:
        contents = file.read()
        print(contents)
        file.close()

In [92]:
reading()

This is the New Data opened the file and written the data


In [101]:
def appending():
    with open("lec25.txt", "a") as file:
        file.write("Am Appeding some data in the existing file")
        
        contents=file.read()
        print(contents)
        file.close()
        

In [102]:
appending()

ValueError: I/O operation on closed file.

In [3]:
people = {"Omkar" : 28, "Roja" : 48, "Roja" : "Musaldhi"}
type(people)

dict

In [8]:
print(people["Roja"])

Musaldhi


In [9]:
fruits = {"Mango":"Yellow", "Apple":"Red", "Grapes":"Green","Banana":"Yellow"}

In [10]:
print(fruits)

{'Mango': 'Yellow', 'Apple': 'Red', 'Grapes': 'Green', 'Banana': 'Yellow'}


In [11]:
print(fruits["Mango"])

Yellow


In [22]:
numbers = {
    1 : "Omkar",
    2 : "Roja",
    3 : "Pakku",
    4 : "Pukku"
}

In [23]:
print ( 1 in numbers)

True


In [24]:
print(numbers.get(1))

Omkar


In [25]:
print(numbers.get(5))

None


In [26]:
print(numbers.get(5, "No number found "))

No number found 
